[client]
showSidebarNavigation = false

[theme]
base = "light"

[auth]
DB_NAME = "aapn_db"
DB_USER_ADMIN = "root"
DB_PASSWORD = "NboBl9u/H/6U3TV4ca7PVFQ1zMZbTTtcbg4ujOvb"
DB_HOST = "localhost"
DB_PORT = 3308

[google_service_account]
